version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.20-nightly
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
  runner:
    image: gitea/act_runner:nightly
    restart: always
    depends_on:
      - server
    volumes:
      - ./data/act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITEA_INSTANCE_URL=http://192.168.0.104:3000/
      - GITEA_RUNNER_REGISTRATION_TOKEN=<<token>>