name: Real-time-intelligence-desktop CI/CD pipeline
run-name: ${{ github.actor }} clean package
on: [push]
jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update and install
        run: apt-get update && apt-get install -y maven && apt-get install -y xvfb && apt-get install -y libxtst6
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check Maven
        run: mvn -v
      - name: Build with Maven in dummy display
        run: xvfb-run mvn clean package