package ru.dimension.ui.laf;

public enum LafColorGroup {
  CONFIG,
  REPORT,
  CHART,
  CHART_PANEL,
  LEGEND_CHART_PANEL,
  BUTTON,
  CONFIG_PANEL,
  TEXTAREA,
  BORDER,
  TABLE_BACKGROUND,
  TABLE_FONT,
  TABLE_FONT_COLOR,
  LABEL_FONT_COLOR,
  RANGE_SELECTED_FONT_COLOR,
  RANGE_NOT_SELECTED_FONT_COLOR,
  CHART_HISTORY_HOUR_FONT,
  CHART_HISTORY_DAY_FONT,
  CHART_HISTORY_MONTH_FONT,
  CHART_HISTORY_YEAR_FONT
}
